"""auto symbol selection and scalping support

Revision ID: 516afd25c064
Revises: 8fca0a31a087
Create Date: 2026-08-25 16:40:07.159636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '516afd25c064'
down_revision: Union[str, None] = '8fca0a31a087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default is required here (unlike the ORM-level `default=` on the
    # model) because these tables already have rows in any real deployment —
    # without it, Postgres can't add a NOT NULL column.
    op.add_column('settings', sa.Column('auto_select_symbols_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('settings', sa.Column('auto_select_max_symbols', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('settings', sa.Column('auto_select_min_volume_usdt', sa.Float(), nullable=False, server_default='5000000'))
    op.add_column('symbols', sa.Column('is_auto_selected', sa.Boolean(), nullable=False, server_default=sa.false()))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symbols', 'is_auto_selected')
    op.drop_column('settings', 'auto_select_min_volume_usdt')
    op.drop_column('settings', 'auto_select_max_symbols')
    op.drop_column('settings', 'auto_select_symbols_enabled')
    # ### end Alembic commands ###
