"""network bandwidth controls

Revision ID: 6027786c89b3
Revises: 1a0cb5ee4242
Create Date: 2026-08-26 22:14:16.444678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6027786c89b3'
down_revision: Union[str, None] = '1a0cb5ee4242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default required: the settings table already has a row in any
    # real deployment.
    op.add_column('settings', sa.Column('stream_all_timeframes', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('settings', sa.Column('orderbook_update_speed_ms', sa.Integer(), nullable=False, server_default='1000'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'orderbook_update_speed_ms')
    op.drop_column('settings', 'stream_all_timeframes')
    # ### end Alembic commands ###
